### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by pge** [pphilippos/ThinkpadL14fix#1]
Hey pphilippos,

first of all: Thanks for the script!
Im getting an error running it: 

```
root@hyperion:~/scripts# ./l14fix2.py 
80
enabled 0
failure 1
pid 10565
rate_limit 0
backlog_limit 8192
lost 0
backlog 0
backlog_wait_time 60000
backlog_wait_time_actual 0
kernel.dmesg_restrict = 0
kernel.sysrq = 1
watchdog 120
tee: /proc/acpi/ibm/fan: Invalid argument
Traceback (most recent call last):
  File "/root/scripts/./l14fix2.py", line 63, in <module>
    tgpu = int(subprocess.getoutput("sensors|grep edge").split("+")[1].split(".")[0])
IndexError: list index out of range
```
Do you have a fix handy?
Thanks,
pge

**Comment by pphilippos** [comment]
Thank you for your comment, what is your output of "sensors|grep edge"?

Mine is 
[philippos@araucaria shm]$ sensors| grep edge
edge:         +37.0°C  

In python 3 this gives
>>> int(subprocess.getoutput("sensors|grep edge").split("+")[1].split(".")[0])
37

Also "tee: /proc/acpi/ibm/fan: Invalid argument" is a bit strange. What kernel are you running? 
Mine has this option

[philippos@araucaria shm]$ cat /proc/acpi/ibm/fan
status:		enabled
speed:		2555
level:		1
commands:	level <level> (<level> is 0-7, auto, disengaged, full-speed)
commands:	enable, disable
commands:	watchdog <timeout> (<timeout> is 0 (off), 1-120 (seconds))

Thanks

**Comment by pge** [comment]
Thanks for the reply!

I seemed to be missing lm-sensors. I have now installed it and the error is: 

```
root@hyperion:~/scripts# ./l14fix2.py 
80
enabled 0
failure 1
pid 832
rate_limit 0
backlog_limit 8192
lost 0
backlog 0
backlog_wait_time 60000
backlog_wait_time_actual 0
kernel.dmesg_restrict = 0
kernel.sysrq = 1
watchdog 120
tee: /proc/acpi/ibm/fan: Invalid argument
Traceback (most recent call last):
  File "/root/scripts/./l14fix2.py", line 64, in <module>
    tdie = int(subprocess.getoutput("sensors|grep Tdie").split("+")[1].split(".")[0])
IndexError: list index out of range
```

"sensors|grep edge" gives me:

`
edge:         +51.0°C  
`

Im on Debian 11 (Buster, Testing) with 

Linux hyperion 5.10.0-7-amd64 #1 SMP Debian 5.10.40-1 (2021-05-28) x86_64 GNU/Linux

And i do get an output on  "cat /proc/acpi/ibm/fan"

```
root@hyperion:~/scripts# cat /proc/acpi/ibm/fan
status:		enabled
speed:		4127
level:		auto
```

**EDIT: I am using Python 3.9**

**Comment by pphilippos** [comment]
Thank you for the followup. It seems that the ThinkPad ACPI needs to be enabled for your machine (I don't remember how, maybe through BIOS settings, and/or kernel parameters). I think it should be easy to find the awnser.

**Comment by pge** [comment]
It seems to be enabled already :( 

```
pgeschke@hyperion:~$ lsmod | grep thinkpad 
thinkpad_acpi         118784  0
nvram                  16384  1 thinkpad_acpi
ledtrig_audio          16384  2 snd_hda_codec_generic,thinkpad_acpi
snd                   110592  19 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek,snd_timer,snd_compress,thinkpad_acpi,snd_soc_core,snd_pcm
rfkill                 28672  9 bluetooth,thinkpad_acpi,cfg80211
battery                20480  1 thinkpad_acpi
video                  53248  1 thinkpad_acpi
```

**Comment by pphilippos** [comment]
From here there are some options for the acpi module. Is it 1 for you? https://wiki.archlinux.org/title/fan_speed_control#Installation_3

**Comment by pge** [comment]
```
pgeschke@hyperion:~$ cat /proc/acpi/ibm/fan
status:		enabled
speed:		4123
level:		auto
```

**Comment by pphilippos** [comment]
See here https://askubuntu.com/questions/1048379/tee-proc-acpi-ibm-fan-invalid-argument

**Comment by pge** [comment]
Alright! Thanks!

I now seem to get:

```
pgeschke@hyperion:~$ cat /proc/acpi/ibm/fan
status:		enabled
speed:		4136
level:		auto
commands:	level <level> (<level> is 0-7, auto, disengaged, full-speed)
commands:	enable, disable
commands:	watchdog <timeout> (<timeout> is 0 (off), 1-120 (seconds))
```

But still the script exits with:

```
root@hyperion:~/scripts# ./l14fix2.py 
80
enabled 0
failure 1
pid 833
rate_limit 0
backlog_limit 8192
lost 0
backlog 0
backlog_wait_time 60000
backlog_wait_time_actual 0
kernel.dmesg_restrict = 0
kernel.sysrq = 1
watchdog 120
Traceback (most recent call last):
  File "/root/scripts/./l14fix2.py", line 64, in <module>
    tdie = int(subprocess.getoutput("sensors|grep Tdie").split("+")[1].split(".")[0])
IndexError: list index out of range
```

**Comment by pphilippos** [comment]
could you paste your "sensors" output? thanks

**Comment by pge** [comment]
Of course!

```
pgeschke@hyperion:~$ sensors
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +46.0°C  

nvme-pci-0100
Adapter: PCI adapter
Composite:    +44.9°C  (low  =  -0.1°C, high = +82.8°C)
                       (crit = +83.8°C)
Sensor 1:     +37.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +38.9°C  (low  = -273.1°C, high = +65261.8°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +62.0°C  (crit = +128.0°C)

thinkpad-isa-0000
Adapter: ISA adapter
fan1:        4132 RPM
temp1:        +62.0°C  
temp2:            N/A  
temp3:         +0.0°C  
temp4:         +0.0°C  
temp5:         +0.0°C  
temp6:         +0.0°C  
temp7:         +0.0°C  
temp8:            N/A  

amdgpu-pci-0700
Adapter: PCI adapter
vddgfx:        1.44 V  
vddnb:       787.00 mV 
edge:         +49.0°C  
power1:       23.00 W  

BAT0-acpi-0
Adapter: ACPI interface
in0:          12.51 V  
```

**Comment by pphilippos** [comment]
Thanks. this is because k10temp is not loaded (sudo modprobe k10temp),
Otherwise, replace 
"sensors|grep Tdie"
with 
"sensors|grep -A1 RPM| tail -1"

**Comment by pge** [comment]
Okay, swapping the grep worked, the k10module did not.
Now i get an error 

```
sudo: ryzenadj: Befehl nicht gefunden
0 0.0 0
sudo: ryzenadj: Befehl nicht gefunden
0 0.0 0
sudo: ryzenadj: Befehl nicht gefunden
0 0.0 0
sudo: ryzenadj: Befehl nicht gefunden
0 0.0 0
sudo: ryzenadj: Befehl nicht gefunden
0 0.0 0

```

"command not found" for ryzenadj

**Comment by pge** [comment]
I've just built ryzenadj - retrying.

**Comment by pge** [comment]
Ohhh, it seems to work! 
That is a much nicer volume! :) 

```
Sucessfully set stapm_limit to 25000
Sucessfully set fast_limit to 25000
Sucessfully set slow_limit to 25000
0 0.0 0
Sucessfully set stapm_limit to 25000
Sucessfully set fast_limit to 25000
Sucessfully set slow_limit to 25000
0 0.0 0
Sucessfully set stapm_limit to 25000
Sucessfully set fast_limit to 25000
Sucessfully set slow_limit to 25000
```

Thanks for you support, @pphilippos !
